### ISSUE TITLE
Nobenega GUI, dokler ni napisana logika igre

### ISSUE THREAD

**Issue by andrejbauer** [stifler9/Dameo#1]
Prosim, da se pobriše tisti razred `Okno`, ki dela nekakšen `JFrame`. Najprej naprogramirajte logiko igre, potem bomo delali uporabniški vmesnik. Namenoma je tako.

**Comment by stifler9** [comment]
Logika je naprogramirana in deluje po pravilih, ki so napisani v readme. Okno in Platno imam samo, da lahko igram. Ali lahko to zbrišem, ko bomo začeli delati uporabniški vmesnik, ali je preveč v napoto?

**Comment by andrejbauer** [comment]
Razlog, zakaj tiščim, da moraš narediti logiko brez GUI je, da te silim v določen način razmišljanja. Napiši si `JUnit` teste, ne pa GUI. Ja, prosim pobriši.

**Comment by andrejbauer** [comment]
A ne bi bilo treba zapreti ta issue z nekim commitom, ki je pobrisal Okno in Platno?

**Comment by andrejbauer** [comment]
Zdi se, da tisti "closes #1" v ea8c1d5d02bdfddf22a64db3f80c4c96c2adb820  ni deloval. Hmm. Sicer pa nisi zares popravil tega issue, ker se `Okno.java` in `Platno.java` še vedno skrivata v `testOkno`, a ne?
