### ISSUE TITLE
Kaj bo počela Nataša?

### ISSUE THREAD

**Issue by andrejbauer** [stifler9/Dameo#4]
Ker @stifler9 ful vse hitro na programira in povozi kodo od @natasataskov, če mu ni všeč, @natasataskov pa danes ni bilo na predavanja, bi bilo dobro vedeti, kako bosta vidva funkcionirala kot ekipa. Prosim, da se pogovorita in tu napišeta, kakšen je plan. Brez plana bo @stifler9 vse napisal sam, @natasataskov pa sploh ne bo imela šanse.

Jaz bi bil najbolj vesel, če bi dejansko začela delati skupaj. Tako, da sedita za kompjuterjem in @natasataskov tipka, @stifler9 pa gleda. Potem se lahko tudi zamenjata, a naj ne tipka samo eden. To bo zelo vzgojno za oba, imam občutek.

Kaj menita?

**Comment by stifler9** [comment]
Jaz se strinjam. Ko se vidiva, se dogovoriva kako naprej in sporočiva.

**Comment by natasataskov** [comment]
Zdaj sva večino naredila skupaj med vajami. Mislim, da je najin projekt dokončan, razen če imaste še vi kakšno pripombo.
